# Header

menu:
  主页: /
  随笔: /tags/随笔/

# SubNav
subnav:
  github: "https://github.com/sssvip"
  #weibo: "#"
  rss: "atom.xml"
  #zhihu: "#"
  #douban: "#"
  mail: "mailto:admin@dxscx.com"
  #facebook: "#"
  google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 1
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: 
# 微信二维码图片地址
weixin: /img/blog.png

# Miscellaneous
google_analytics: ''
favicon: /favicon.ico

#你的头像url
avatar: /img/user.jpg

#是否开启分享
share_jia: false

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: sssvip

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于'

friends:
  申请友连: mailto:admin@dxscx.com

aboutme: <div style="color:red;padding:50px;"><br><br> 追求“精品之路”，像做学问一样做技术! <br><br>更多资料<a href="https://blog.dxscx.com/2016/12/09/resume/">查看简历</a><br><br>托管于github,谨慎关注！</div>